---
# tasks file for swarm_node_join

- name: Retrieve swarm status
  ansible.builtin.shell: 
    cmd: docker info 2>null | grep "Swarm:" | sed 's/^[[:space:]]//g' | cut -d ' ' -f2
  register: swarm_status

- name: Join node
  community.docker.docker_swarm:
    state: join
    join_token: "{{ hostvars['DUMMY_HOST']['swarm_token'] }}"
    remote_addrs: [ '{{ swarm_mgr_host }}:2377' ]
  when: "'active' not in swarm_status.stdout_lines"
  become: yes

